; PlatformIO Project Configuration File
; para sa Water Level Monitoring System (Backend Queen Edition)

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Dito nakalagay ang mga libraries para sa JSON at Sensors
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    teckel12/NewPing @ ^1.9.7

; Speed ng Serial Monitor para mabasa ang logs
monitor_speed = 115200